before_install: npm install -g grunt-cli
install: npm install
language: node_js
node_js:
  - "0.10"

sudo: false

env:
  global:
  - GH_REF: github.com/Syonet/bootstrap.git

  # GH_TOKEN
  - secure: fhji+OFnObAO+hH+3O4cv6S09ZXBFGyx4Nx2l8pW/1mS9Bg7hRUMYQsYAXFJrn9miIwioYhtsfQC4bNhy0r8R7J6Gh/MWsbvH9Rr3xSqHxVqWc+2lNJIefu7SiXILGOlg82Vg6a++G7YsX/r8gvu+SQmp44RGwmh2LQ5+zIj03E=

after_success:
  - ./build/scripts/docs-update.sh
